### ISSUE TITLE
SMS Phone Tap Code Cipher

### ISSUE THREAD

**Issue by Loevland** [Sagensagen/UiTHack23#115]
Får oppgitt tastene man trykker på for å skrive SMS på gamle nokiaer. Flagget er dekodet versjon av tastetrykkene.

https://www.dcode.fr/multitap-abc-cipher

**Comment by Sagensagen** [comment]
Er det ikke det jeg og Jørgen har mekka? O.o

**Comment by Loevland** [comment]
> Er det ikke det jeg og Jørgen har mekka? O.o

Ah okei, trodde dem va forskjellig sjøl om d va samme "theme"😅

**Comment by Sagensagen** [comment]
Kan hende jeg misforstod, men hørtes lik ut. Bare at vi sender hver tast til et endpoint og må gjøres fort nok

**Comment by Loevland** [comment]
> Kan hende jeg misforstod, men hørtes lik ut. Bare at vi sender hver tast til et endpoint og må gjøres fort nok

Mulig dem blir litt for lik, lage bare en anna type cipher 👌🏼 👌🏼
