### ISSUE TITLE
Reverse Computation From Executable

### ISSUE THREAD

**Issue by marius-j-i** [Sagensagen/UiTHack23#12]
Imagine there is some binary executable on a computer accessed via SSH. 
Somebody can execute it with argument vector values or stdin stream to get out some warped or meaningful information.
The executable should internally use the flag as part of this computation and try to keep this secret. 

Examples of executables might be reversible hashes (which must be bad) or just a sequence of operations.
A way to solve this could be by looking at the assembly composition of `objdump -d <exec>`. 
A way to make it even harder is to allow execution and disallow reads for the SSH user, and instead hint that different inputs yield insight into the computations made by performing mass input and displaying them in a certain way such as plotting.

Key-words:
- information flow
- SSH
- compiling
- executable
- assembly

**Comment by Sagensagen** [comment]
Nais. Just remember one can easy be blinded by the actual difficulty of the task when we hold the solution/creates the task our self.
