### ISSUE TITLE
Image Corruption & Noise

### ISSUE THREAD

**Issue by marius-j-i** [Sagensagen/UiTHack23#13]
Ideas for corruption: 

Overlay video frames, e.g. a cartoon episode, and put those images three-by-three together into a single image on each color channel.
In between a random sequence of frames insert flag-image.

Symmetrically encrypt an image with the flag as the key and hint that the flag has some format constraints.
A solution might be to brute force decryption with varying keys of a fixed length.

**Comment by Sagensagen** [comment]
@marius-j-i 
UU nice. What kind of difficulty would your grade this? In terms of points to earn?

**Comment by marius-j-i** [comment]
I have no point of reference for what points goes where.
